### ISSUE TITLE
Error in TwofaHelper.php after update

### ISSUE THREAD

**Issue by BarryJohnson01** [humhub/twofa#45]
Error: Cannot use object of type yii\web\Cookie as array in /var/www/vhosts/lostboysworld.org/protected/modules/twofa/helpers/TwofaHelper.php:345
Stack trace:
#0 /var/www/vhosts/lostboysworld.org/protected/modules/twofa/models/CheckCode.php(77): humhub\modules\twofa\helpers\TwofaHelper::rememberBrowser()
#1 /var/www/vhosts/lostboysworld.org/protected/modules/twofa/controllers/CheckController.php(48): humhub\modules\twofa\models\CheckCode->save()
#2 [internal function]: humhub\modules\twofa\controllers\CheckController->actionIndex()
#3 /var/www/vhosts/lostboysworld.org/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /var/www/vhosts/lostboysworld.org/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#5 /var/www/vhosts/lostboysworld.org/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('', Array)
#6 /var/www/vhosts/lostboysworld.org/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('twofa/check', Array)
#7 /var/www/vhosts/lostboysworld.org/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request))
#8 /var/www/vhosts/lostboysworld.org/index.php(32): yii\base\Application->run()
#9 {main}

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/twofa/pull/46.
just for info it was implemented here https://github.com/humhub/twofa/pull/40/files#diff-10c3a3fac8e08e7e863b1b79506bad343204fddd183fa8df5a59827deca4e82dR344
